name: Generate Javadoc

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to generate Javadoc from'
        required: true
        default: 'main'
        type: string

jobs:
  generate-javadoc:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      
      - name: Generate Javadoc
        run: ./gradlew :library:generateJavadoc
      
      - name: Upload Javadoc
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: library/build/docs/javadoc
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: library/build/docs/javadoc
          branch: gh-pages
          clean: true